title:  "Thiago K. Rosin Page"
author:
  name: "Thiago Knakiwicz Rosin"
  email: "contact@thiagorosin.com"

github: "thikrosin"
facebook: "thiago.rosin"
linkedin: "br.linkedin.com/in/thiagokrosin/en"
gravatar_hash: "6c2ba00757797a59839154deb5811221"

# Handling Reading
encoding: utf-8

# Conversion
highlighter:  pygments
markdown:   redcarpet

# Outputting
timezone:  America/Sao_Paulo
permalink: pretty

